[package]
name = "Urocissa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
arrayvec = { version = "0.7.4", features = ["serde"] }
bitcode = { version = "0.6.3", features = ["arrayvec"] }
blake3 = "1.5.1"
chrono = "0.4.38"
dashmap = { version = "6.0.1", features = ["rayon"] }
env_logger = "0.11.5"
futures = "0.3.30"
image = "0.25.1"
image_hasher = "2.0.0"
indicatif = "0.17.8"
kamadak-exif = "0.5.5"
log = "0.4.22"
notify = "6.1.1"
path-clean = "1.0.1"
rand = "0.8.5"
rayon = "1.10.0"
redb = "2.1.3"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
rocket = { version = "0.5.1", features = ["json"] }
rocket_seek_stream = "0.2.6"
serde = { version = "1.0.204", features = ["derive", "rc"] }
serde_json = "1.0.120"
thumbhash = "0.1.0"
tokio = { version = "1.38.0", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4"] }
walkdir = "2.5.0"
zune-jpeg = "0.4.11"
